#!/usr/bin/env python3
"""Open a follow-up PR for unsupported upstream DSW metamodels."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def main() -> None:
    """CLI entrypoint."""

    parser = argparse.ArgumentParser(
        description="create or update a DSW compatibility follow-up pull request",
    )
    parser.add_argument("--report", type=Path, required=True, help="Discovery report file.")
    parser.add_argument(
        "--report-path",
        type=Path,
        default=Path("docs/compatibility/unsupported-metamodels.md"),
        help="Path to commit the report to.",
    )
    parser.add_argument(
        "--repository",
        default=os.environ.get("GITHUB_REPOSITORY", ""),
        help="GitHub repository, for example owner/name.",
    )
    parser.add_argument(
        "--base",
        default=os.environ.get("GITHUB_REF_NAME", "master"),
        help="Base branch for the follow-up PR.",
    )
    parser.add_argument(
        "--branch",
        default="automation/dsw-compat-review",
        help="Branch to push the follow-up report to.",
    )
    parser.add_argument(
        "--title",
        default="Review new DSW document-template metamodel compatibility",
        help="Pull request title.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Write the report locally but do not commit, push, or create a PR.",
    )
    args = parser.parse_args()

    if not args.repository:
        raise SystemExit("--repository is required when GITHUB_REPOSITORY is not set")
    if not args.report.is_file():
        raise SystemExit(f"Report file does not exist: {args.report}")

    report = args.report.read_text(encoding="utf-8").strip()
    rendered_report = render_follow_up_report(report)

    if args.dry_run:
        args.report_path.parent.mkdir(parents=True, exist_ok=True)
        args.report_path.write_text(rendered_report, encoding="utf-8")
        print(f"INFO: wrote {args.report_path} (dry run)")
        return

    branch_existed = checkout_start_ref(branch=args.branch, base=args.base)
    args.report_path.parent.mkdir(parents=True, exist_ok=True)
    args.report_path.write_text(rendered_report, encoding="utf-8")

    run(["git", "add", str(args.report_path)])

    if not has_staged_changes():
        if branch_existed:
            print("INFO: Compatibility follow-up report is unchanged; ensuring PR exists.")
            create_or_update_pr(
                repository=args.repository,
                branch=args.branch,
                base=args.base,
                title=args.title,
                body=render_pr_body(args.report_path),
            )
            return
        print("INFO: Compatibility follow-up report is unchanged; no remote branch to update.")
        return

    configure_git_identity()
    run(["git", "commit", "-m", "docs: record unsupported DSW metamodels"])
    run(["git", "push", "--force-with-lease", "origin", f"HEAD:refs/heads/{args.branch}"])
    create_or_update_pr(
        repository=args.repository,
        branch=args.branch,
        base=args.base,
        title=args.title,
        body=render_pr_body(args.report_path),
    )


def render_follow_up_report(report: str) -> str:
    """Render a committed investigation report."""

    return (
        "# Unsupported DSW Metamodel Compatibility\n\n"
        "The scheduled upstream compatibility check found a Science Europe template "
        "version whose `metamodelVersion` is not covered by `config/dsw-compat.yml`.\n\n"
        "This file is generated by CI as an investigation note. Do not treat it as "
        "proof that a runtime is compatible. A maintainer still needs to smoke-test "
        "the DSW server, document worker, dsw-tdk version, import path, and PDF "
        "render path before adding a runtime row.\n\n"
        "## Discovery Report\n\n"
        f"{report}\n\n"
        "## Maintainer Checklist\n\n"
        "- [ ] Pick a candidate DSW server/document-worker version from the official "
        "metamodel hint.\n"
        "- [ ] Pick a matching `dsw-tdk` version.\n"
        "- [ ] Smoke-test KM import, template package/import, preview render, and PDF "
        "render.\n"
        "- [ ] Add the proven runtime to `config/dsw-compat.yml`.\n"
        "- [ ] Run `make sync-dsw-runtime-matrix`.\n"
        "- [ ] Confirm clean scaffold release assets are produced for the new tag.\n"
    )


def render_pr_body(report_path: Path) -> str:
    """Render the pull request body."""

    return (
        "CI detected at least one upstream Science Europe template tag whose "
        "`metamodelVersion` is not covered by the checked-in DSW runtime matrix.\n\n"
        f"This PR records the discovery report in `{report_path.as_posix()}` so a "
        "maintainer can smoke-test the right DSW/TDK pairing before updating "
        "`config/dsw-compat.yml`.\n\n"
        "The PR is intentionally not expected to be merged as-is unless the runtime "
        "row is added and verified."
    )


def configure_git_identity() -> None:
    """Configure a deterministic CI git identity when none is set."""

    run(["git", "config", "user.name", "github-actions[bot]"])
    run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])


def checkout_start_ref(*, branch: str, base: str) -> bool:
    """Check out the automation start point without binding a local branch.

    The workflow pushes the generated commit with ``HEAD:refs/heads/<branch>``,
    so a local branch is unnecessary. Staying detached avoids failures when a
    maintainer already has the automation branch checked out in another
    worktree.
    """

    if remote_branch_exists(branch):
        run(["git", "fetch", "origin", f"refs/heads/{branch}:refs/remotes/origin/{branch}"])
        run(["git", "checkout", "--detach", f"origin/{branch}"])
        return True
    run(["git", "checkout", "--detach", fetch_base_ref(base)])
    return False


def fetch_base_ref(base: str) -> str:
    """Fetch and return the origin ref used to start a new automation branch."""

    origin_ref = f"origin/{base}"
    fetch_result = subprocess.run(
        ["git", "fetch", "origin", f"refs/heads/{base}:refs/remotes/{origin_ref}"],
        check=False,
    )
    if fetch_result.returncode != 0 or not git_ref_exists(origin_ref):
        raise SystemExit(
            f"Base branch origin/{base} does not exist or could not be fetched. "
            "Refusing to create a compatibility PR from the current checkout HEAD."
        )
    return origin_ref


def remote_branch_exists(branch: str) -> bool:
    """Return whether the remote automation branch already exists."""

    return (
        subprocess.run(
            ["git", "ls-remote", "--exit-code", "--heads", "origin", branch],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        ).returncode
        == 0
    )


def git_ref_exists(ref: str) -> bool:
    """Return whether a local git ref exists."""

    return (
        subprocess.run(
            ["git", "rev-parse", "--verify", "--quiet", ref],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        ).returncode
        == 0
    )


def has_staged_changes() -> bool:
    """Return whether the index has staged changes."""

    return (
        subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            check=False,
        ).returncode
        != 0
    )


def create_or_update_pr(
    *,
    repository: str,
    branch: str,
    base: str,
    title: str,
    body: str,
) -> None:
    """Create or update the follow-up pull request."""

    body_file = Path(".cache/dsw-compat-pr-body.md")
    body_file.parent.mkdir(parents=True, exist_ok=True)
    body_file.write_text(body + "\n", encoding="utf-8")

    existing = subprocess.run(
        ["gh", "pr", "view", branch, "--repo", repository, "--json", "url", "--jq", ".url"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    if existing.returncode == 0 and existing.stdout.strip():
        run(
            [
                "gh",
                "pr",
                "edit",
                branch,
                "--repo",
                repository,
                "--title",
                title,
                "--body-file",
                str(body_file),
            ]
        )
        print(f"INFO: Updated existing PR: {existing.stdout.strip()}")
        return

    run(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            repository,
            "--base",
            base,
            "--head",
            branch,
            "--title",
            title,
            "--body-file",
            str(body_file),
        ]
    )


def run(args: list[str]) -> None:
    """Run a command."""

    subprocess.run(args, check=True)


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: command failed with exit code {exc.returncode}: {exc.cmd}", file=sys.stderr)
        raise SystemExit(exc.returncode) from exc
