from __future__ import annotations

import hashlib
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "ci" / "stage_release_assets.py"
PUBLISH_SCRIPT = ROOT / "scripts" / "ci" / "publish_clean_scaffold_releases.py"


def run(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, check=False, text=True, capture_output=True)


def test_stage_release_assets_copies_archives_and_checksums(tmp_path: Path) -> None:
    package = tmp_path / "template.zip"
    package.write_text("package\n", encoding="utf-8")
    preview = tmp_path / "preview.pdf"
    preview.write_text("pdf\n", encoding="utf-8")
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "template.json").write_text("{}\n", encoding="utf-8")
    (workspace / "src").mkdir()
    (workspace / "src" / "content.html.j2").write_text("<p>ok</p>\n", encoding="utf-8")
    output_dir = tmp_path / "release"

    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(output_dir),
            "--notes-title",
            "Science Europe zh-Hant v1.30.1",
            "--notes-body",
            "Generated by CI.",
            "--asset",
            f"{package}=dsw-science-europe-zh-hant-v1.30.1.zip",
            "--optional-asset",
            f"{preview}=test-project-v1.30.1.pdf",
            "--archive-dir",
            f"{workspace}=clean-workspace-v1.30.1.zip",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert (output_dir / "dsw-science-europe-zh-hant-v1.30.1.zip").read_text(
        encoding="utf-8"
    ) == "package\n"
    assert (output_dir / "test-project-v1.30.1.pdf").read_text(encoding="utf-8") == "pdf\n"
    with zipfile.ZipFile(output_dir / "clean-workspace-v1.30.1.zip") as archive:
        assert sorted(archive.namelist()) == [
            "workspace/src/content.html.j2",
            "workspace/template.json",
        ]

    checksums = (output_dir / "SHA256SUMS").read_text(encoding="utf-8")
    expected_hash = hashlib.sha256(b"package\n").hexdigest()
    assert f"{expected_hash}  dsw-science-europe-zh-hant-v1.30.1.zip" in checksums

    notes = (output_dir / "release-notes.md").read_text(encoding="utf-8")
    assert "# Science Europe zh-Hant v1.30.1" in notes
    assert "Generated by CI." in notes
    assert "`SHA256SUMS`" in notes


def test_stage_release_assets_skips_missing_optional_assets(tmp_path: Path) -> None:
    package = tmp_path / "template.zip"
    package.write_text("package\n", encoding="utf-8")
    output_dir = tmp_path / "release"

    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(output_dir),
            "--notes-title",
            "Optional asset demo",
            "--asset",
            str(package),
            "--optional-asset",
            str(tmp_path / "missing.pdf"),
            "--optional-archive-dir",
            f"{tmp_path / 'missing-dir'}=missing.zip",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert sorted(path.name for path in output_dir.iterdir()) == [
        "SHA256SUMS",
        "release-notes.md",
        "template.zip",
    ]


def test_stage_release_assets_fails_for_missing_required_asset(tmp_path: Path) -> None:
    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(tmp_path / "release"),
            "--notes-title",
            "Missing demo",
            "--asset",
            str(tmp_path / "missing.zip"),
        ],
    )

    assert result.returncode != 0
    assert "Required release asset file is missing" in result.stderr


def test_publish_clean_scaffold_releases_stages_assets_in_dry_run(tmp_path: Path) -> None:
    """The clean scaffold publisher should own release staging and gh calls."""

    outputs = tmp_path / "outputs"
    package = (
        outputs
        / "document-templates"
        / "dsw-science-europe"
        / "v1.30.1"
        / "zh-Hant"
        / "scaffold"
        / "dsw-science-europe-zh-hant-scaffold-1.30.1.zip"
    )
    package.parent.mkdir(parents=True)
    package.write_text("package\n", encoding="utf-8")
    workspace = outputs / "upstream-workspaces" / "dsw-science-europe" / "v1.30.1"
    workspace.mkdir(parents=True)
    (workspace / "upstream.json").write_text("{}\n", encoding="utf-8")
    preview = outputs / "project-render" / "dsw-science-europe" / "v1.30.1" / "zh-Hant" / "scaffold"
    preview.mkdir(parents=True)
    (preview / "test-project.pdf").write_text("pdf\n", encoding="utf-8")

    result = run(
        [
            sys.executable,
            str(PUBLISH_SCRIPT),
            "--outputs-root",
            str(outputs),
            "--release-root",
            str(outputs / "release-assets" / "clean-scaffold"),
            "--repository",
            "owner/repo",
            "--run-id",
            "123",
            "--commit-sha",
            "abc123",
            "--dry-run",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    release_dir = outputs / "release-assets" / "clean-scaffold" / "v1.30.1"
    assert sorted(path.name for path in release_dir.iterdir()) == [
        "SHA256SUMS",
        "clean-preview-dsw-science-europe-v1.30.1.zip",
        "clean-workspace-dsw-science-europe-v1.30.1.zip",
        "dsw-science-europe-zh-hant-scaffold-1.30.1.zip",
        "release-notes.md",
    ]
    notes = (release_dir / "release-notes.md").read_text(encoding="utf-8")
    assert "Generated by owner/repo run 123 from commit abc123." in notes
    assert "not finished public translations" in notes


def test_publish_clean_scaffold_releases_succeeds_without_packages(tmp_path: Path) -> None:
    """Missing packages should be a no-op for runtimes that produced no artifacts."""

    result = run(
        [
            sys.executable,
            str(PUBLISH_SCRIPT),
            "--outputs-root",
            str(tmp_path / "outputs"),
            "--repository",
            "owner/repo",
            "--dry-run",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "No clean scaffold packages were produced" in result.stdout


def test_publish_clean_scaffold_releases_help() -> None:
    """The clean scaffold publisher should expose a help screen."""

    result = run([sys.executable, str(PUBLISH_SCRIPT), "--help"])

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Publish clean scaffold GitHub Release assets" in result.stdout
    assert "--dry-run" in result.stdout
