from __future__ import annotations

import hashlib
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "ci" / "stage_release_assets.py"


def run(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, check=False, text=True, capture_output=True)


def test_stage_release_assets_copies_archives_and_checksums(tmp_path: Path) -> None:
    package = tmp_path / "template.zip"
    package.write_text("package\n", encoding="utf-8")
    preview = tmp_path / "preview.pdf"
    preview.write_text("pdf\n", encoding="utf-8")
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "template.json").write_text("{}\n", encoding="utf-8")
    (workspace / "src").mkdir()
    (workspace / "src" / "content.html.j2").write_text("<p>ok</p>\n", encoding="utf-8")
    output_dir = tmp_path / "release"

    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(output_dir),
            "--notes-title",
            "Science Europe zh-Hant v1.30.1",
            "--notes-body",
            "Generated by CI.",
            "--asset",
            f"{package}=dsw-science-europe-zh-hant-v1.30.1.zip",
            "--optional-asset",
            f"{preview}=test-project-v1.30.1.pdf",
            "--archive-dir",
            f"{workspace}=clean-workspace-v1.30.1.zip",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert (output_dir / "dsw-science-europe-zh-hant-v1.30.1.zip").read_text(
        encoding="utf-8"
    ) == "package\n"
    assert (output_dir / "test-project-v1.30.1.pdf").read_text(encoding="utf-8") == "pdf\n"
    with zipfile.ZipFile(output_dir / "clean-workspace-v1.30.1.zip") as archive:
        assert sorted(archive.namelist()) == [
            "workspace/src/content.html.j2",
            "workspace/template.json",
        ]

    checksums = (output_dir / "SHA256SUMS").read_text(encoding="utf-8")
    expected_hash = hashlib.sha256(b"package\n").hexdigest()
    assert f"{expected_hash}  dsw-science-europe-zh-hant-v1.30.1.zip" in checksums

    notes = (output_dir / "release-notes.md").read_text(encoding="utf-8")
    assert "# Science Europe zh-Hant v1.30.1" in notes
    assert "Generated by CI." in notes
    assert "`SHA256SUMS`" in notes


def test_stage_release_assets_skips_missing_optional_assets(tmp_path: Path) -> None:
    package = tmp_path / "template.zip"
    package.write_text("package\n", encoding="utf-8")
    output_dir = tmp_path / "release"

    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(output_dir),
            "--notes-title",
            "Optional asset demo",
            "--asset",
            str(package),
            "--optional-asset",
            str(tmp_path / "missing.pdf"),
            "--optional-archive-dir",
            f"{tmp_path / 'missing-dir'}=missing.zip",
        ],
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert sorted(path.name for path in output_dir.iterdir()) == [
        "SHA256SUMS",
        "release-notes.md",
        "template.zip",
    ]


def test_stage_release_assets_fails_for_missing_required_asset(tmp_path: Path) -> None:
    result = run(
        [
            sys.executable,
            str(SCRIPT),
            "--output-dir",
            str(tmp_path / "release"),
            "--notes-title",
            "Missing demo",
            "--asset",
            str(tmp_path / "missing.zip"),
        ],
    )

    assert result.returncode != 0
    assert "Required release asset file is missing" in result.stderr
